### ISSUE TITLE
Improve Search Response Interface

### ISSUE THREAD

**Issue by BenRKarl** [googleads/google-ads-python#111]
Related to this issue: https://github.com/googleads/google-ads-python/issues/89

It seems valuable for the response from a search request to contain more information that exists on the `SearchGoogleAdsResponse` message. Namely `total_results_count`, `next_page_token` (in case someone wants to customize pagination logic) and `results` so that the first page of results can be accessed without initiating iteration, for example if an object is filtered by ID and only one record is returned.

**Comment by leoblanchard** [comment]
Is there any update on the issue flagged in #89 ? The iterator still doesn't seem to have the total_results_count attribute mentioned in the documentation, only num_results which returns 0 until it's been iterated through. This means another search request is required to use the actual iterator after first checking the results count.

**Comment by BenRKarl** [comment]
@leoblanchard unfortunately not yet, the only way to retrieve the results count at the moment is to actually iterate through all the results.

**Comment by BenRKarl** [comment]
This is fixed with version 10.0.0 (#399). The response from a `Search` call is a Pager object that delegates attribute accesses to it's `SearchGoogleAdsResponse` instance, so you can do:

```py
response = google_ads_service.search(customer_id=customer_id, query=query)
response.total_results_count
response.results
```

See the [migration guide](https://developers.devsite.corp.google.com/google-ads/api/docs/client-libs/python/library-version-10) for more details.

**Comment by adcore-dev** [comment]
@BenRKarl Hey, still can't get total_results_count from search, any ideas? it always return 0

**Comment by BenRKarl** [comment]
@adcore-dev you probably need to set the `return_total_results_count` flag on the request. For example see the [get_ad_groups example](https://github.com/googleads/google-ads-python/blob/main/examples/basic_operations/get_ad_groups.py#L40). If you add the below line before passing the request into the `search` method it should work.

```
search_request.return_total_results_count = True
```

**Comment by adcore-dev** [comment]
@BenRKarl Thanks. I'll check and let you know. It will be good to have an improved documentation and examples.
