### ISSUE TITLE
Threads created and not destroyed with each client

### ISSUE THREAD

**Issue by dgmp88** [googleads/google-ads-python#239]
Each time you search on a client, new threads are created that are not destroyed. e.g. if you need to use many clients and run 

```python
def test():
    auth_string = """****"""
    client = google_ads.client.GoogleAdsClient.load_from_string(auth_string)
    service = client.get_service("GoogleAdsService")
    res = service.search(
        "****", "select campaign.resource_name from campaign limit 1"
    )
    res = list(res)


for i in range(10000):
    test()
```
Then run `watch -n1 "ps -eLf | wc -l"` in another terminal, you can see the number of threads creeping up. After a while you'll reach your machines thread limit then have lots of system wide problems. 

If you comment out the last line turning the results generator into a list, the problem disappears, so I think the thread creation is occurring there? 

As far as I can tell there isn't a `.close()` function on the client or service I'm missing?

**Comment by wihl** [comment]
What version of the library are you using? We just released v5 yesterday.

**Comment by dgmp88** [comment]
It was on the previous version, but I just tested on 5 and still see the thread count creeping up. I'm running on Ubuntu 18.04.

**Comment by BenRKarl** [comment]
@dgmp88 If you put a `print(len(threading.enumerate()))` call after the call to `test` you can see the thread count increase by one after each call. I'd expect the threads to get closed after the generator is finished with the request. I'm going to file an issue with the `gRPC` team to see if they can help identify the issue.

**Comment by BenRKarl** [comment]
@dgmp88 can you clarify which version of the `grpcio` module you have installed when you see this? I don't see the issue when I use the newest `1.27.2`

**Comment by dgmp88** [comment]
Thanks for the quick replies! 

threading - good point, that's far simpler! 

I just checked, I'm also using 1.27.2 and still seeing this.

**Comment by dgmp88** [comment]
I also just updated everything i could think of (had an older version of `grpc-cpp`), but still seeing the issue

**Comment by BenRKarl** [comment]
@dgmp88 which version of Python are you using? And are you using a virtualenv?

**Comment by BenRKarl** [comment]
@dgmp88 Can you confirm whether you see this issue if you downgrade google-auth to version 1.7.1? I can consistently repro with 1.7.2 and later, but not with 1.7.1.

**Comment by dgmp88** [comment]
I'm using python 3.7 with anaconda (pip for installing the google ads api) and was on google-auth 1.11.2 . 

Yep, it's google-auth! Good find.  Threads don't increase on 1.7.1, and do on 1.7.2 for me as well.

Thanks so much for the speedy diagnosis! I'll downgrade for the time being.

**Comment by BenRKarl** [comment]
@dgmp88 I opened [this issue](https://github.com/googleapis/google-auth-library-python/issues/455) with the Auth team, you can track progress there. Until there's a change on their end the best way forward is to pin `google-auth` to `1.7.1`

**Comment by BenRKarl** [comment]
Version 1.12.0 of `google-auth` was released which fixes this issue, when installing `google-ads-python` it will get downloaded automatically so I'm going to close this issue. If anyone has this problem again make sure to update your dependencies and verify you have a `>= 1.12.0` version of `google-auth` installed.
